### ISSUE TITLE
I'd love to see an option to "Unlist this post from the Quick Edit area in WP for each page/post.

### ISSUE THREAD

**Issue by garymgordon** [brainstormforce/unlist-posts#127]
I'd love to see an option to "Unlist this post" from the Quick Edit area in WP for each page/post in addition to the current location under EDIT. This would just help to make it easier to access. If possible, thank you.

### Is your feature request related to a problem? Please describe.
See above

### Describe the solution you'd like
Just add a checkbox option for this on the Quick Edit screen area.

**Comment by themak1985** [comment]
Came here to request the same thing - would love a simple checkbox on quickedit.

**Comment by spyrosvl** [comment]
[unlist-posts-admin.php](https://github.com/user-attachments/files/27692728/unlist-posts-admin.php)

This should do the trick. Just include it via your child theme.
@Nikschavan want me to do a pull request?

**Comment by garymgordon** [comment]
Thanks, but could this feature be added directly in the plugin itself rather than a separate file? Please let me know.

Thanks, Gary

Something like this:   https://app.screencast.com/mnSR1RaVLStys

**Comment by Nikschavan** [comment]
I just merged this feature in #141, I will release this in a day or two

**Comment by spyrosvl** [comment]
@Nikschavan just wondering if you could "prop" me on the 1.2.0 release about the above contribution 😊

**Comment by garymgordon** [comment]
Nikhil,

I hope you don't mind me emailing you about this, but the Unlist Posts &
Pages plugin, when I use the "Bulk Actions" and choose "Bulk Edit" and if I
select "Unlist" as shown below, while it does say the pages are unlisted,
the pages still show when I visit the page. Example:
https://stepaheadweb.com/home/  This page is set to "Unlist" but it still
shows up. What do you think? Please let me know.

[image: image.png]

Gary Gordon
